import { BsQrCodeScan } from "react-icons/bs";
import { SidebarMenuItem } from "../types/menu";
import ROUTES from "./ROUTES";
import {
  CiBadgeDollar,
  CiBag1,
  CiBank,
  CiBoxList,
  CiBoxes,
  CiCoins1,
  CiDatabase,
  CiDeliveryTruck,
  CiFaceSmile,
  CiHome,
  CiLocationOn,
  CiMedicalClipboard,
  CiMoneyBill,
  CiPaperplane,
  CiSpeaker,
  CiSquarePlus,
  CiUser,
} from "react-icons/ci";
import { BiHome } from "react-icons/bi";
import {
  HiArrowUpOnSquareStack,
  HiBanknotes,
  HiBuildingLibrary,
  HiBuildingOffice2,
  HiCalculator,
  HiChartPie,
  HiClipboardDocument,
  HiClipboardDocumentList,
  HiDocumentArrowUp,
  HiDocumentCheck,
  HiDocumentDuplicate,
  HiDocumentPlus,
  HiMiniBanknotes,
  HiMiniCube,
  HiMiniHome,
  HiMiniHomeModern,
  HiMiniQrCode,
  HiMiniTruck,
  HiMiniUserGroup,
  HiPaperAirplane,
  HiShoppingCart,
  HiSquare3Stack3D,
  HiTableCells,
  HiTruck,
  HiUser,
  HiUserGroup,
  HiUserPlus,
  HiUsers,
} from "react-icons/hi2";

const menuItems = {
  dashboard: { label: "Home", icon: HiMiniHome, path: ROUTES.home },
  warehouses: {
    label: "Warehouses",
    icon: HiMiniHomeModern,
    path: ROUTES.warehouses,
  },
  departments: {
    label: "Departments",
    icon: HiBuildingOffice2,
    path: ROUTES.departments,
  },
  positions: {
    label: "Positions",
    icon: HiMiniUserGroup,
    path: ROUTES.positions,
  },
  payrolls: { label: "Payrolls", icon: HiBanknotes, path: ROUTES.payroll },
  financialReports: {
    label: "Financial Reports",
    icon: HiChartPie,
    path: ROUTES.financialReports,
  },
  // expenses: { label: "Expenses", icon: CiLocationOn, path: ROUTES.expenses },
  userManagement: {
    label: "User Management",
    icon: HiUserGroup,
    path: ROUTES.userManagement,
  },
  enrollment: {
    label: "User Enrollment",
    icon: HiUserPlus,
    path: ROUTES.enrollment,
  },
  stockRecords: {
    label: "Stock Records",
    icon: HiTableCells,
    path: ROUTES.stockRecords,
  },
  stockIn: {
    label: "Stock In",
    icon: HiClipboardDocument,
    path: ROUTES.stockIn,
  },
  externalStockRecords: {
    label: "External Stock Records",
    icon: HiMiniCube,
    path: ROUTES.externalStockRecords,
  },
  inventoryItems: {
    label: "Inventory Items",
    icon: HiSquare3Stack3D,
    path: ROUTES.inventoryItems,
  },
  inventoryTransfers: {
    label: "Inventory Transfers",
    icon: HiPaperAirplane,
    path: ROUTES.inventoryTransfers,
  },
  purchases: {
    label: "Purchases",
    icon: HiShoppingCart,
    path: ROUTES.purchases,
  },
  sales: { label: "Sales", icon: HiMiniBanknotes, path: ROUTES.sales },
  externalDispatch: {
    label: "Logistics Dispatch",
    icon: HiMiniTruck,
    path: ROUTES.externalDispatch,
  },
  internalDispatch: {
    label: "Dispatch (From Warehouse)",
    icon: HiArrowUpOnSquareStack,
    path: ROUTES.internalDispatch,
  },
  transit: { label: "Transit", icon: HiTruck, path: ROUTES.transit },
  scanWaybill: {
    label: "Scan Waybill",
    icon: HiMiniQrCode,
    path: ROUTES.scanWaybill,
  },
  receivedTrucks: {
    label: "Received Trucks",
    icon: HiDocumentCheck,
    path: ROUTES.receivedVehicles,
  },
  dispatchedTrucks: {
    label: "Dispatched Trucks",
    icon: HiDocumentArrowUp,
    path: ROUTES.dispatchedVehicles,
  },
  requests: {
    label: "Requests",
    icon: HiDocumentPlus,
    path: ROUTES.requests,
  },
  productionRuns: {
    label: "Production Runs",
    icon: HiClipboardDocumentList,
    path: ROUTES.productionRuns,
  },
  productSubmissions: {
    label: "Product Submissions",
    icon: HiDocumentDuplicate,
    path: ROUTES.productSubmissions,
  },
  employees: {
    label: "Employees",
    icon: HiUsers,
    path: ROUTES.employees,
  },
};

const {
  dashboard,
  warehouses,
  departments,
  positions,
  payrolls,
  userManagement,
  enrollment,
  stockRecords,
  externalStockRecords,
  inventoryItems,
  inventoryTransfers,
  purchases,
  sales,
  externalDispatch,
  internalDispatch,
  transit,
  scanWaybill,
  receivedTrucks,
  dispatchedTrucks,
  requests,
  productionRuns,
  productSubmissions,
  employees,
  // expenses,
  financialReports,
  stockIn,
} = menuItems;

export const superAdminMenuItems: SidebarMenuItem[] = [
  dashboard,
  warehouses,
  departments,
  positions,
  payrolls,
  financialReports,
  userManagement,
  enrollment,
  stockRecords,
  stockIn,
  externalStockRecords,
  inventoryItems,
  inventoryTransfers,
  purchases,
  sales,
  externalDispatch,
  internalDispatch,
  transit,
  scanWaybill,
  receivedTrucks,
  dispatchedTrucks,
  requests,
  productionRuns,
  productSubmissions,
  employees,
];

export const adminMenuItems: SidebarMenuItem[] = [
  dashboard,
  warehouses,
  departments,
  positions,
  payrolls,
  financialReports,
  userManagement,
  enrollment,
  stockRecords,
  externalStockRecords,
  inventoryItems,
  inventoryTransfers,
  purchases,
  sales,
  externalDispatch,
  internalDispatch,
  transit,
  scanWaybill,
  receivedTrucks,
  dispatchedTrucks,
  productionRuns,
  employees,
];

export const productionMenuItems: SidebarMenuItem[] = [
  dashboard,
  stockRecords,
  requests,
  productionRuns,
  productSubmissions,
];
export const inventoryMenuItems: SidebarMenuItem[] = [
  dashboard,
  stockRecords,
  stockIn,
  inventoryItems,
  internalDispatch,
  transit,
  scanWaybill,
  receivedTrucks,
  dispatchedTrucks,
  requests,
  productSubmissions,
];
export const accountingMenuItems: SidebarMenuItem[] = [
  dashboard,
  payrolls,
  financialReports,
  // expenses,
  purchases,
  sales,
];
export const logisticsMenuItems: SidebarMenuItem[] = [
  dashboard,
  externalDispatch,
  transit,
  receivedTrucks,
];
export const managerMenuItems: SidebarMenuItem[] = [
  dashboard,
  departments,
  positions,
  payrolls,
  financialReports,
  userManagement,
  enrollment,
  stockRecords,
  inventoryItems,
  sales,
  transit,
  receivedTrucks,
  dispatchedTrucks,
  requests,
  productionRuns,
  productSubmissions,
  employees,
  // expenses,
];
export const defaultMenuItems: SidebarMenuItem[] = [menuItems.dashboard];
