import { HiCreditCard, HiTable } from "react-icons/hi";
import { SidebarMenuItem } from "../types/menu";
import ROUTES from "./ROUTES";
import {
  HiArchiveBox,
  HiArrowUpOnSquareStack,
  HiBanknotes,
  HiBuildingOffice2,
  HiChartPie,
  HiClipboardDocument,
  HiClipboardDocumentList,
  HiDocumentArrowUp,
  HiDocumentCheck,
  HiDocumentDuplicate,
  HiDocumentPlus,
  HiMiniBanknotes,
  HiMiniCube,
  HiMiniHome,
  HiMiniHomeModern,
  HiMiniQrCode,
  HiMiniTruck,
  HiMiniUserGroup,
  HiPaperAirplane,
  HiShoppingCart,
  HiSquare3Stack3D,
  HiTableCells,
  HiTruck,
  HiUserGroup,
  HiUserPlus,
  HiUsers,
} from "react-icons/hi2";

const menuItems = {
  dashboard: { label: "Home", icon: HiMiniHome, path: ROUTES.home },
  warehouses: {
    label: "Warehouses",
    icon: HiMiniHomeModern,
    path: ROUTES.warehouses,
  },
  departments: {
    label: "Departments",
    icon: HiBuildingOffice2,
    path: ROUTES.departments,
  },
  positions: {
    label: "Positions",
    icon: HiMiniUserGroup,
    path: ROUTES.positions,
  },
  payrolls: { label: "Payrolls", icon: HiBanknotes, path: ROUTES.payroll },
  financialReports: {
    label: "Financial Reports",
    icon: HiChartPie,
    path: ROUTES.financialReports,
  },
  // expenses: { label: "Expenses", icon: CiLocationOn, path: ROUTES.expenses },
  userManagement: {
    label: "User Management",
    icon: HiUserGroup,
    path: ROUTES.userManagement,
  },
  enrollment: {
    label: "User Enrollment",
    icon: HiUserPlus,
    path: ROUTES.enrollment,
  },
  stockRecords: {
    label: "Stock Records",
    icon: HiTableCells,
    path: ROUTES.stockRecords,
  },
  stockIn: {
    // label: "Stock In",
    label: "Waste Record",
    icon: HiClipboardDocument,
    path: ROUTES.stockIn,
  },
  externalStockRecords: {
    label: "External Stock Records",
    icon: HiMiniCube,
    path: ROUTES.externalStockRecords,
  },
  inventoryItems: {
    label: "Inventory Items",
    icon: HiSquare3Stack3D,
    path: ROUTES.inventoryItems,
  },
  inventoryTransfers: {
    label: "Inventory Transfers",
    icon: HiPaperAirplane,
    path: ROUTES.inventoryTransfers,
  },
  purchases: {
    label: "Purchases",
    icon: HiShoppingCart,
    path: ROUTES.purchases,
  },
  sales: { label: "Sales", icon: HiMiniBanknotes, path: ROUTES.sales },
  externalDispatch: {
    label: "Logistics Dispatch",
    icon: HiMiniTruck,
    path: ROUTES.externalDispatch,
  },
  internalDispatch: {
    label: "Dispatch (From Warehouse)",
    icon: HiArrowUpOnSquareStack,
    path: ROUTES.internalDispatch,
  },
  transit: { label: "Transit", icon: HiTruck, path: ROUTES.transit },
  scanWaybill: {
    label: "Scan Waybill",
    icon: HiMiniQrCode,
    path: ROUTES.scanWaybill,
  },
  receivedTrucks: {
    label: "Received Trucks",
    icon: HiDocumentCheck,
    path: ROUTES.receivedVehicles,
  },
  dispatchedTrucks: {
    label: "Dispatched Trucks",
    icon: HiDocumentArrowUp,
    path: ROUTES.dispatchedVehicles,
  },
  requests: {
    label: "Requests",
    icon: HiDocumentPlus,
    path: ROUTES.requests,
  },
  productionRuns: {
    label: "Production Runs",
    icon: HiClipboardDocumentList,
    path: ROUTES.productionRuns,
  },
  finishedProducts: {
    label: "Finished Products",
    icon: HiArchiveBox,
    path: ROUTES.finishedProducts,
  },
  productSubmissions: {
    label: "Product Submissions",
    icon: HiDocumentDuplicate,
    path: ROUTES.productSubmissions,
  },
  employees: {
    label: "Employees",
    icon: HiUsers,
    path: ROUTES.employees,
  },
  dailyProduction: {
    label: "Daily Production",
    icon: HiTable,
    path: ROUTES.dailyProduction,
  },
  invoices: {
    label: "Invoices",
    icon: HiCreditCard,
    path: ROUTES.invoices,
  },
};

const {
  dashboard,
  warehouses,
  departments,
  positions,
  payrolls,
  userManagement,
  enrollment,
  stockRecords,
  externalStockRecords,
  inventoryItems,
  inventoryTransfers,
  purchases,
  sales,
  externalDispatch,
  internalDispatch,
  transit,
  scanWaybill,
  receivedTrucks,
  dispatchedTrucks,
  requests,
  productionRuns,
  finishedProducts,
  productSubmissions,
  employees,
  // expenses,
  financialReports,
  stockIn,
  dailyProduction,
  invoices,
} = menuItems;

export const superAdminMenuItems: SidebarMenuItem[] = [
  dashboard,
  warehouses,
  departments,
  positions,
  payrolls,
  financialReports,
  invoices,
  userManagement,
  enrollment,
  stockRecords,
  stockIn,
  externalStockRecords,
  inventoryItems,
  inventoryTransfers,
  purchases,
  sales,
  externalDispatch,
  internalDispatch,
  transit,
  scanWaybill,
  receivedTrucks,
  dispatchedTrucks,
  requests,
  productionRuns,
  finishedProducts,
  productSubmissions,
  dailyProduction,
  employees,
];

export const adminMenuItems: SidebarMenuItem[] = [
  dashboard,
  warehouses,
  // departments,
  // positions,
  // payrolls,
  // financialReports,
  // invoices,
  // userManagement,
  // enrollment,
  stockRecords,
  externalStockRecords,
  inventoryItems,
  inventoryTransfers,
  // purchases,
  // sales,
  externalDispatch,
  internalDispatch,
  transit,
  scanWaybill,
  receivedTrucks,
  dispatchedTrucks,
  productionRuns,
  finishedProducts,
  dailyProduction,
  // employees,
];

export const productionMenuItems: SidebarMenuItem[] = [
  dashboard,
  stockRecords,
  requests,
  productionRuns,
  finishedProducts,
  productSubmissions,
  dailyProduction,
];
export const inventoryMenuItems: SidebarMenuItem[] = [
  dashboard,
  stockRecords,
  stockIn,
  inventoryItems,
  internalDispatch,
  transit,
  scanWaybill,
  receivedTrucks,
  dispatchedTrucks,
  requests,
  productSubmissions,
  dailyProduction,
];
export const accountingMenuItems: SidebarMenuItem[] = [
  dashboard,
  payrolls,
  financialReports,
  invoices,
  // expenses,
  purchases,
  sales,
  stockRecords,
  dispatchedTrucks,
  receivedTrucks,
  dailyProduction,
];
export const logisticsMenuItems: SidebarMenuItem[] = [
  dashboard,
  externalDispatch,
  transit,
  receivedTrucks,
];
export const managerMenuItems: SidebarMenuItem[] = [
  dashboard,
  // departments,
  // positions,
  // payrolls,
  // financialReports,
  // invoices,
  // userManagement,
  // enrollment,
  stockRecords,
  inventoryItems,
  // sales,
  transit,
  receivedTrucks,
  dispatchedTrucks,
  requests,
  productionRuns,
  productSubmissions,
  // employees,
  dailyProduction,
  // expenses,
];
export const defaultMenuItems: SidebarMenuItem[] = [menuItems.dashboard];
