const ROUTES = {
  home: "/",
  warehouses: "/warehouses",
  enrollment: "/enrollment",
  expenses: "/expenses",
  financialReports: "/financial-reports",
  invoices: "/invoices",
  departments: "/departments",
  positions: "/positions",
  payroll: "/payroll",
  inventoryItems: "/inventory-items",
  purchases: "/purchases",
  sales: "/sales",
  stockRecords: "/stock-records",
  stockIn: "/stockIn",
  externalStockRecords: "/external-stock-records",
  externalDispatch: "/external-dispatch",
  internalDispatch: "/internal-dispatch",
  transit: "/transit",
  scanWaybill: "/scan-waybill",
  dispatchedVehicles: "/dispatched-vehicles",
  receivedVehicles: "/received-vehicles",
  requests: "/requests",
  productionRuns: "/production-runs",
  finishedProducts: "/finished-products",
  productSubmissions: "/product-submissions",
  inventoryTransfers: "/inventory-transfers",
  employees: "/employees",
  transportFees: "/transportFees",
  userManagement: "/user-management",
  dailyProduction: "/daily-production",
  production: "/production",
  inventory: "/inventory",
  users: "/users",
  logistics: "/logistics",
  company: "/company",
  hr: "/hr",
};

export default ROUTES;
